add_newline = true
scan_timeout = 20
format = """
$time\
$character $directory$git_branch$git_status$python$nodejs$rust$golang$memory_usage$battery$cmd_duration
â†’ """

[time]
format = "ğŸ•’ [$time]($style) "
time_format = "%H:%M:%S"
style = "dimmed green"
disabled = false

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true
home_symbol = "~"

[git_branch]
symbol = "î‚  "
style = "bold magenta"

[git_status]
style = "white"
format = "$all_status "
untracked = "âœ±${count} "
modified = "âœ${count} "
staged = "+${count} "
ahead = "â†‘${count} "
behind = "â†“${count} "
conflicted = "â€¼ "

[python]
symbol = "ğŸ "
style = "bold green"
format = "$symbol[${version}]($style) "

[nodejs]
symbol = "îœ˜ "
style = "bold blue"
format = "$symbol[${version}]($style) "

[rust]
symbol = "ğŸ¦€ "
style = "bold red"
format = "$symbol[${version}]($style) "

[golang]
symbol = "ğŸ¹ "
style = "bold cyan"
format = "$symbol[${version}]($style) "

[memory_usage]
disabled = false
threshold = 70
symbol = "ğŸ§  "
style = "bold blue"
format = "$symbol[$ram_pct]($style) "

[battery]
disabled = false
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡"
discharging_symbol = "ğŸ”Œ"
unknown_symbol = "â“"
empty_symbol = "ğŸª«"
format = "$symbol[$percentage]($style) "

[cmd_duration]
min_time = 2000
format = "â± [$duration]($style) "
style = "yellow"

[character]
success_symbol = "[âœ”](bold green)"
error_symbol = "[âœ˜](bold red)"
vicmd_symbol = "[ğŸ•ª](bold blue)"
